<div class="container pt-5 mt-5 row justify-content-center">
    <div class="card">
        <div class="card-body">
            <form class="form-inline" method='POST' action='/login/'>
                <div class="form-group mx-sm-3 mb-2">
                    <label for="inputPassword2" class="sr-only">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Log In</button>
            </form>
        </div>
    </div>
</div>