<?php
foreach ($articles as $article) : ?>
    <div class="card mt-3">
        <div class="card-body">
            <?php /* echo $article->text(); */ ?>
            <p><?php echo $article->getDate(); ?></p>
            <p><?php echo $article->getSlug(); ?></p>
            <p><?php echo $article->getPath(); ?></p>
            <p><?php echo implode('|', $article->getCategories()); ?></p>
            <p><?php echo $article->getLink(); ?></p>
        </div>
    </div>
<?php endforeach; ?>