<?php

use function SimpleBase\Functions\prepareCategories;
?>
<aside class="categories">
    <?php echo prepareCategories($categories, ['ul' => 'class="categories"']); ?>
</aside>
<?php foreach ($articles as $article) : ?>
    <article>
        <p><?php echo $article->text(); ?></p>
        <p><?php echo $article->getDate(); ?></p>
        <p><?php echo $article->getSlug(); ?></p>
        <p><?php echo $article->getPath(); ?></p>
        <p><?php echo implode(' --> ', $article->getCategories()); ?></p>
        <p><?php echo $article->getLink(); ?></p>
    </article>
<?php endforeach; ?>