<?php

use function SimpleBase\Functions\prepareCategories;
?>
<aside class="categories">
    <?php
    $styles = [
        'li' => 'class="categories-item"',
        'ul' => 'class="categories"',
    ];
    echo prepareCategories($categories, $styles); ?>
</aside>
<?php foreach ($articles as $article) : ?>
    <article>
        <p><?php echo $article->text(); ?></p>
        <p><?php echo $article->getDate(); ?></p>
        <p><?php echo $article->getSlug(); ?></p>
        <p><?php echo $article->getPath(); ?></p>
        <p><?php echo implode(' --> ', $article->getCategories()); ?></p>
        <p><?php echo $article->getLink(); ?></p>
    </article>
<?php endforeach; ?>