<?php

use SimpleBase\User\User;

$user = new User();

$current = 'active';
$isPrivate = mb_strpos($_SERVER['REQUEST_URI'], '/private/') === 0 ? $current : '';
$isShared = mb_strpos($_SERVER['REQUEST_URI'], '/shared/') === 0 ? $current : '';
$isBlog = mb_strpos($_SERVER['REQUEST_URI'], '/blog/') === 0 ? $current : '';

?>
<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">

    <title>FFTF</title>
    <meta name="description" content="Simple Base">
    <meta name="author" content="Alfred Sorrow">
    <link rel="stylesheet" href="/front/prism.css" />
    <script src="/front/prism.js"></script>

    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/front/style.css">

</head>

<body>

    <div class="container">
        <header>
            <nav class='main-nav'>
                <a href="/" class="blog-name">FFTF </a>
                <div class="nav-sections">
                    <a class="nav-link <?php echo $isBlog ?>" href="/blog/">Blog</a>
                    <?php if (!$user->isAuthorized()) : ?>
                        <a class="nav-link last" href="/login/">Login</a>
                    <?php endif; ?>
                    <?php if ($user->isAuthorized()) : ?>
                        <a class="nav-link <?php echo $isShared ?>" href="/shared/">Shared</a>
                        <a class="nav-link <?php echo $isPrivate ?>" href="/private/">Private</a>
                        <a class="nav-link last" href="/logout/">Logout</a>
                    <?php endif; ?>

                </div>
            </nav>
        </header>
        <div class="container">
            <?php
            include $templatePath;
            ?>
        </div>
    </div>
</body>

</html>